stages:
  - build
  - deploy

build_dev_app:
  image: node:14.5.0-alpine
  stage: build
  only :
    - development
  before_script :
    - echo VUE_APP_ENCRYPTION_KEY=$VUE_APP_ENCRYPTION_KEY_DEV >> .env
    - echo VUE_APP_CRYPTO_KEY=$VUE_APP_CRYPTO_KEY_DEV >> .env
    - echo VUE_APP_CRYPTO_IV=$VUE_APP_CRYPTO_IV_DEV >> .env
    - echo VUE_APP_ENV=$VUE_APP_ENV_DEV >> .env
  script:
    - npm install
    - npm run build
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

build_staging_app:
  image: node:14.5.0-alpine
  stage: build
  only :
    - staging
  before_script :
    - echo VUE_APP_ENCRYPTION_KEY=$VUE_APP_ENCRYPTION_KEY_STAGE >> .env
    - echo VUE_APP_CRYPTO_KEY=$VUE_APP_CRYPTO_KEY_STAGE >> .env
    - echo VUE_APP_CRYPTO_IV=$VUE_APP_CRYPTO_IV_STAGE >> .env
    - echo VUE_APP_ENV=$VUE_APP_ENV_STAGE >> .env
  script:
    - npm install
    - npm run build
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

build_production_app:
  image: node:14.5.0-alpine
  stage: build
  only :
    - master
  before_script :
    - echo VUE_APP_ENCRYPTION_KEY=$VUE_APP_ENCRYPTION_KEY_PROD >> .env
    - echo VUE_APP_CRYPTO_KEY=$VUE_APP_CRYPTO_KEY_PROD >> .env
    - echo VUE_APP_CRYPTO_IV=$VUE_APP_CRYPTO_IV_PROD >> .env
    - echo VUE_APP_ENV=$VUE_APP_ENV_PROD >> .env
  script:
    - npm install
    - npm run build
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

upload_to_s3_dev:
  stage: deploy
  only :
    - development
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws configure set region ap-south-1
    - aws s3 rm s3://$S3_BUCKET_DEV --recursive
    - aws s3 cp dist s3://$S3_BUCKET_DEV --recursive

upload_to_s3_staging:
  stage: deploy
  only :
    - staging
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws configure set region ap-south-1
    - aws s3 rm s3://$S3_BUCKET_STAGE --recursive
    - aws s3 cp dist s3://$S3_BUCKET_STAGE --recursive

upload_to_s3_prod:
  stage: deploy
  only :
    - master
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws configure set region ap-south-1
    - aws s3 rm s3://$S3_BUCKET_PROD --recursive
    - aws s3 cp dist s3://$S3_BUCKET_PROD --recursive